### ISSUE TITLE
单词使用问题

### ISSUE THREAD

**Issue by SuzukiHonoka** [cokemine/hotaru_theme#3]
https://github.com/CokeMine/Hotaru_theme/blob/a28790d802ff63ba941ef31558828c5f4e5845a4/src/components/Body.vue#L16

ROM: Read Only MEMORY
不符合“存储空间”定义。
应更换为 Storage 为最佳。

**Comment by CokeMine** [comment]
确实，Storage感觉有些长了。或许直接改为中文“硬盘”也不错？顺便把RAM也改成中文的“内存”，我记得逗比大佬写的前端就是这样命名的
